definitions:
  pkg.Response:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      validation:
        additionalProperties:
          type: string
        type: object
    type: object
  request.ForgetPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        maxLength: 50
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  request.ResetPasswordRequest:
    properties:
      new_password:
        minLength: 6
        type: string
      token:
        type: string
    required:
    - new_password
    - token
    type: object
info:
  contact: {}
paths:
  /api/admin/auth/login:
    post:
      consumes:
      - application/json
      description: Login Admin
      parameters:
      - description: Login Admin
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Login Admin
      tags:
      - Auth-Admin
  /api/superadmin/auth/login:
    post:
      consumes:
      - application/json
      description: Login Superadmin
      parameters:
      - description: Login Superadmin
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Login Superadmin
      tags:
      - Auth-Superadmin
  /api/user/auth/forget-password:
    post:
      consumes:
      - application/json
      description: Send password reset email
      parameters:
      - description: Forget Password
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.ForgetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Forget Password
      tags:
      - Auth-User
  /api/user/auth/login:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: Login User
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Login User
      tags:
      - Auth-User
  /api/user/auth/register:
    post:
      consumes:
      - application/json
      description: Register User
      parameters:
      - description: Register User
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Register User
      tags:
      - Auth-User
  /api/user/auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset password using token
      parameters:
      - description: Reset Password
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/pkg.Response'
      summary: Reset Password
      tags:
      - Auth-User
swagger: "2.0"
